services:
  frontend:
    build: ./frontend
    container_name: ${FRONTEND_CONTAINER_NAME}
    environment:
      - VUE_APP_PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - ruleta
    depends_on:
      - backend
      - data-base
    restart: always
  backend:
    build: ./backend
    container_name: ${BACKEND_CONTAINER_NAME}
    environment:
      - PORT=${BACKEND_PORT}
      - SECRET_KEY=${BACKEND_SECRET_KEY}
      - DATABASE_URL=${BACKEND_DATABASE_URL}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - data-base
    networks:
      - ruleta
    restart: always
  data-base:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - ruleta
    restart: always
  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/start.sh:/start.sh
    entrypoint: /bin/bash -c "chmod +x /start.sh && /start.sh"
    depends_on:
      - frontend
      - backend
    networks:
      - ruleta
    restart: always
networks:
  ruleta:
    driver: bridge